import {
  Accordion,
  AccordionActions,
  AccordionDetails,
  AccordionSummary,
  Alert,
  AppBar,
  Avatar,
  AvatarGroup,
  Badge,
  BottomNavigation,
  BottomNavigationAction,
  Box,
  Breadcrumbs, 
  Card,
  Checkbox,
  Chip,
  CircularProgress,
  Collapse,
  Dialog,
  Divider, 
  Fab,
  ImageList,
  ImageListItem,
  ImageListItemBar,
  LinearProgress,
  Link, 
  Menu, 
  Paper,
  Popover,
  Radio,
  RadioGroup,
  Rating,
  Select,
  Skeleton,
  Slider,
  Snackbar,
  SnackbarContent,
  SpeedDial,
  SpeedDialAction,
  SpeedDialIcon,
  Switch,
  Tab,
  Tabs, 
  ToggleButton,
  ToggleButtonGroup,
  Tooltip,
  Typography,
} from "@mui/material";
import Marquee from "react-fast-marquee";
import { Masonry } from "@mui/lab";
import ReactlyIconButton from "./ReactlyIconButton/ReactlyIconButton";
import ReactlyPagination from "./ReactlyPagination/ReactlyPagination";
import ReactlyImage from "./ReactlyImage/ReactlyImage";
import ReactlyFieldset from "./ReactlyFieldset/ReactlyFieldset";
import ReactlyButton from "./ReactlyButton/ReactlyButton";
import ReactlyTextbox from "./ReactlyTextbox/ReactlyTextbox";
import ReactlyDrawer from "./ReactlyDrawer/ReactlyDrawer";
import ReactlyList from "./ReactlyList/ReactlyList";
import ReactlyCarousel from "./ReactlyCarousel/ReactlyCarousel";
import ReactlyDatagrid from "./ReactlyDatagrid/ReactlyDatagrid";

const ReactlySpacer = () => <Box sx={{ flexGrow: 1 }} />;

export const LibraryComponents = {
  Alert,
  AvatarGroup,
  Badge,
  BottomNavigation,
  BottomNavigationAction,
  Carousel: ReactlyCarousel,
  DataGrid: ReactlyDatagrid,
  Dialog,
  Divider,
  Drawer: ReactlyDrawer,
  Fab,
  Fieldset: ReactlyFieldset,

  IconButton: ReactlyIconButton,
  Image: ReactlyImage,
  ImageList,
  ImageListItem,
  ImageListItemBar,
  Switch,
  Tab,
  Tabs,
  Textbox: ReactlyTextbox,
  ToggleButton,
  ToggleButtons: ToggleButtonGroup,
  Tooltip,
  LinearProgress,
  Link,
  List: ReactlyList,
  Marquee,
  Masonry,
  Menu,
  Pagination: ReactlyPagination,
  Paper,
  Popover,
  Radio,
  RadioGroup,
  Rating,
  Select,
  Skeleton,
  Slider,
  Snackbar,
  SnackbarContent,
  Spacer: ReactlySpacer,
  SpeedDial,
  SpeedDialAction,
  SpeedDialIcon,
  Box,
  Breadcrumbs,
  Button: ReactlyButton,
  Card,
  Checkbox,
  Chip,
  CircularProgress,
  Collapse,
  Accordion,
  AccordionActions,
  AccordionDetails,
  AccordionSummary,
  AppBar,
  Avatar,
  Typography,
};
